class Rbac:

    COMMENT = 1
    PUBLISH = 2
    UNPUBLISH = 3
    WRITE_ARTICLES = 4
    MODERATE_COMMENTS = 5
    ADMINISTRATOR = 6
    MANAGE_CONTENT = 7
    MANAGE_MEMBERS = 8
    MANAGE_ACCESS = 9
    TRANSFER_OWNERSHIP = 10
