# User registration
EMAIL_REGISTRATION = 0
FB_REGISTRATION = 1
GOOGLE_REGISTRATION = 2
TWITTER_REGISTRATION = 3
LINKEDIN_REGISTRATION = 4

REGISTERED_WITH = {
    EMAIL_REGISTRATION: 'email',
    FB_REGISTRATION: 'fb',
    GOOGLE_REGISTRATION: 'google',
    TWITTER_REGISTRATION: 'twitter',
    LINKEDIN_REGISTRATION: 'linkedin'
}