# User registration
PROFIREADER_REGISTRATION = 0
GOOGLE_REGISTRATION = 1
FACEBOOK_REGISTRATION = 2
LINKEDIN_REGISTRATION = 3
TWITTER_REGISTRATION = 4
MICROSOFT_REGISTRATION = 5
YAHOO_REGISTRATION = 6

REGISTERED_WITH = {
    PROFIREADER_REGISTRATION: 'profireader',
    GOOGLE_REGISTRATION: 'google',
    FACEBOOK_REGISTRATION: 'facebook',
    LINKEDIN_REGISTRATION: 'linkedin',
    TWITTER_REGISTRATION: 'twitter',
    MICROSOFT_REGISTRATION: 'microsoft',
    YAHOO_REGISTRATION: 'yahoo',
}

REGISTERED_WITH_FLIPPED = dict(zip(REGISTERED_WITH.values(),
                                   REGISTERED_WITH.keys()))

DB_ALIAS_ID = {
    REGISTERED_WITH[PROFIREADER_REGISTRATION]: 'profireader_id',
    REGISTERED_WITH[GOOGLE_REGISTRATION]: 'google_id',
    REGISTERED_WITH[FACEBOOK_REGISTRATION]: 'facebook_id',
    REGISTERED_WITH[LINKEDIN_REGISTRATION]: 'linkedin_id',
    REGISTERED_WITH[TWITTER_REGISTRATION]: 'twitter_id',
    REGISTERED_WITH[MICROSOFT_REGISTRATION]: 'microsoft_id',
    REGISTERED_WITH[YAHOO_REGISTRATION]: 'yahoo_id',
}
