# User registration
EMAIL_REGISTRATION = 0
FB_REGISTRATION = 1
GOOGLE_REGISTRATION = 2
TWITTER_REGISTRATION = 3
LINKEDIN_REGISTRATION = 4
MICROSOFT_REGISTRATION = 5
YAHOO_REGISTRATION = 6

REGISTERED_WITH = {
    EMAIL_REGISTRATION: 'email',
    FB_REGISTRATION: 'facebook',
    GOOGLE_REGISTRATION: 'google',
    TWITTER_REGISTRATION: 'twitter',
    LINKEDIN_REGISTRATION: 'linkedin',
    MICROSOFT_REGISTRATION: 'microsoft',
    YAHOO_REGISTRATION: 'yahoo',
}

REGISTERED_WITH_FLIPPED = dict(zip(REGISTERED_WITH.values(),
                                   REGISTERED_WITH.keys()))

DB_ALIAS_UID = {
    REGISTERED_WITH[EMAIL_REGISTRATION]: 'email',
    REGISTERED_WITH[FB_REGISTRATION]: 'fb_uid',
    REGISTERED_WITH[GOOGLE_REGISTRATION]: 'google_uid',
    REGISTERED_WITH[TWITTER_REGISTRATION]: 'twitter_uid',
    REGISTERED_WITH[LINKEDIN_REGISTRATION]: 'linkedin_uid',
    REGISTERED_WITH[MICROSOFT_REGISTRATION]: 'microsoft_uid',
    REGISTERED_WITH[YAHOO_REGISTRATION]: 'yahoo_uid',
}
